<a href="https://colab.research.google.com/github/Abishek711/SORT/blob/main/data_preprossing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [59]:
dataset= pd.read_csv("Jio - Jio Prepaid Planes (version 1).csv")
x= dataset.iloc[:, :-1]
y= dataset.iloc[: , 7]

In [60]:
print(x)

    Days  Price( in Rupee)  No. of Customers(in millions)  Price/Day  \
0     28               209                             73   7.464286   
1     24               179                             35   7.458333   
2     20               149                             12   7.450000   
3    336              2545                             10   7.574405   
4     84               666                            112   7.928571   
5     56               479                             56   8.553571   
6     30               259                             14   8.633333   
7     28               239                             16   8.535714   
8     23               199                             29   8.652174   
9     14               119                              5   8.500000   
10   365              2879                             81   7.887671   
11    56               533                             13   9.517857   
12    28               299                             53  10.67

In [61]:
print(y)

0     1.0
1     1.0
2     1.0
3     1.5
4     1.5
5     1.5
6     1.5
7     1.5
8     1.5
9     1.5
10    2.0
11    2.0
12    2.0
13    2.0
14    3.0
15    3.0
Name: Data_per_day, dtype: float64


In [66]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=0, strategy='mean')
imputer= imputer.fit(x.iloc[:, 5:7])
x.iloc[:, 5:7]= imputer.transform(x.iloc[:, 5:7])

In [67]:
print(x)

    Days  Price( in Rupee)  No. of Customers(in millions)  Price/Day  \
0     28               209                             73   7.464286   
1     24               179                             35   7.458333   
2     20               149                             12   7.450000   
3    336              2545                             10   7.574405   
4     84               666                            112   7.928571   
5     56               479                             56   8.553571   
6     30               259                             14   8.633333   
7     28               239                             16   8.535714   
8     23               199                             29   8.652174   
9     14               119                              5   8.500000   
10   365              2879                             81   7.887671   
11    56               533                             13   9.517857   
12    28               299                             53  10.67

In [68]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x= np.array(ct.fit_transform(x))

In [69]:
print(x)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.09000000e+02 7.30000000e+01
  7.46428571e+00 2.72446429e+03 5.21428571e+00 2.08571429e+03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.79000000e+02 3.50000000e+01
  7.45833333e+00 2.72229167e+03 3.04166667e+00 1.21666667e+03]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.49000000e+02 1.20000000e+01
  7.45000000e+00 2.71925000e+03 4.08481625e+02 1.63392650e+05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 2.54500000e+03 1.00000000e+01
  7.57440476e+00 2.76465774e+03 4.08481625e+02 1.63392650e+05]
 [0.

In [70]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y= le.fit_transform(y)

In [71]:
print(y)

[0 0 0 1 1 1 1 1 1 1 2 2 2 2 3 3]


In [72]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state= 0)

In [73]:
print(x_train)

[[0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.49000000e+02 6.00000000e+00
  1.08260870e+01 3.95152174e+03 1.07252174e+03 4.29008696e+05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 6.66000000e+02 1.12000000e+02
  7.92857143e+00 2.89392857e+03 1.29270833e+02 5.17083333e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.49000000e+02 1.20000000e+01
  7.45000000e+00 2.71925000e+03 4.08481625e+02 1.63392650e+05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 1.19900000e+03 4.00000000e+00
  1.42738095e+01 5.20994048e+03 4.08481625e+02 1.63392650e+05]
 [0.

In [74]:
print(x_test)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.79000000e+02 3.50000000e+01
  7.45833333e+00 2.72229167e+03 3.04166667e+00 1.21666667e+03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.59000000e+02 1.40000000e+01
  8.63333333e+00 3.15116667e+03 3.86508929e+02 1.54603571e+05]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.99000000e+02 2.90000000e+01
  8.65217391e+00 3.15804348e+03 3.93385740e+02 1.57354296e+05]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.19000000e+02 5.00000000e+00
  8.50000000e+00 3.10250000e+03 3.37842262e+02 1.35136905e+05]]


In [75]:
print(y_train)

[2 1 0 3 2 1 3 2 1 0 1 2]


In [76]:
print(y_test)

[0 1 1 1]


In [77]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train[:, 5:]= sc.fit_transform(x_train[:, 5:])
x_test[:, 5:]= sc.transform(x_test[:, 5:])

In [78]:
print(x_train)

[[ 0.          0.          1.          0.          0.          0.
  -0.4472136  -0.4472136  -0.30151134 -0.30151134 -0.64407423 -0.88049527
   0.47681339  0.47681339  2.05469318  2.05469318]
 [ 0.          0.          0.          0.          0.          0.
  -0.4472136   2.23606798 -0.30151134 -0.30151134 -0.17541821  2.13834564
  -0.68594729 -0.68594729 -1.06483119 -1.06483119]
 [ 0.          1.          0.          0.          0.          0.
  -0.4472136  -0.4472136  -0.30151134 -0.30151134 -0.75646177 -0.70961748
  -0.87799598 -0.87799598 -0.14142379 -0.14142379]
 [ 0.          0.          0.          0.          0.          0.
  -0.4472136   2.23606798 -0.30151134 -0.30151134  0.42360735 -0.93745453
   1.86036983  1.86036983 -0.14142379 -0.14142379]
 [ 0.          0.          0.          0.          0.          0.
  -0.4472136  -0.4472136  -0.30151134  3.31662479  2.31171795  1.25547708
  -0.70236037 -0.70236037 -0.14142379 -0.14142379]
 [ 0.          0.          0.          0.    

In [79]:
print(x_test)

[[ 0.          0.          0.          1.          0.          0.
  -0.4472136  -0.4472136  -0.30151134 -0.30151134 -0.72274551 -0.05458596
  -0.87465185 -0.87465184 -1.48229696 -1.48229696]
 [ 0.          0.          0.          0.          0.          1.
  -0.4472136  -0.4472136  -0.30151134 -0.30151134 -0.63283548 -0.65265822
  -0.40312933 -0.40312933 -0.21409201 -0.21409201]
 [ 0.          0.          1.          0.          0.          0.
  -0.4472136  -0.4472136  -0.30151134 -0.30151134 -0.700268   -0.22546375
  -0.39556869 -0.39556869 -0.19134898 -0.19134898]
 [ 1.          0.          0.          0.          0.          0.
  -0.4472136  -0.4472136  -0.30151134 -0.30151134 -0.79017803 -0.9089749
  -0.45663543 -0.45663543 -0.37504266 -0.37504266]]


In [80]:
print(y_train)

[2 1 0 3 2 1 3 2 1 0 1 2]


In [81]:
print(y_test)

[0 1 1 1]
